export function setlist () {
  return {
    sets: [
      {
        jpName: 'Aチャンネル',
        abbr: 'ACH',
        enName: 'A-Channel',
        releaseDate: 'Jan 27, 2012',
      },
      {
        jpName: 'あの日見た花の名前を僕達はまだ知らない。',
        abbr: 'AHB',
        enName: 'anohana: The Flower We Saw That Day',
        releaseDate: 'Dec 22, 2011',
      },
      {
        jpName: '劇場版 あの日見た花の名前を僕達はまだ知らない。',
        abbr: 'AHB2',
        enName: '   anohana: The Flower We Saw That Day The Movie',
        releaseDate: 'Aug 27, 2021',
      },
      {
        jpName: 'AKB0048',
        abbr: 'AKB',
        enName: 'AKB0048',
        releaseDate: 'Jan 25, 2013',
      },
      {
        jpName: 'アマガミSS+ plus',
        abbr: 'AMG',
        enName: 'Amagami SS+ plus',
        releaseDate: 'Dec 27, 2013',
      },
      {
        jpName: '学戦都市アスタリスク',
        abbr: 'AW',
        enName: 'The Asterisk War',
        releaseDate: 'May 27, 2016',
      },
      {
        jpName: 'ぼくたちは勉強ができない！',
        abbr: 'BBD',
        enName: 'We Never Learn: BOKUBEN',
        releaseDate: 'May 29, 2020',
      },
      {
        jpName: '化物語',
        abbr: 'BKM',
        enName: 'Bakemonogatari',
        releaseDate: 'May 28, 2012',
      },
      {
        jpName: 'カードキャプターさくら',
        abbr: 'CCS',
        enName: 'Cardcaptor Sakura',
        releaseDate: 'Aug 8, 2014',
      },
      {
        jpName: 'ClariS',
        abbr: 'ClariS',
        enName: 'Claris',
        releaseDate: '??? ??, 2013',
      },
      {
        jpName: 'カーニバル・ファンタズム',
        abbr: 'CP',
        enName: 'Carnival Phantasm',
        releaseDate: 'Apr 27, 2012',
      },
      {
        jpName: 'ハイスクールＤ×Ｄ ＢｏｒＮ',
        abbr: 'DDB',
        enName: 'High School DxD BorN',
        releaseDate: 'Jun 8, 2016',
      },
      {
        jpName: 'ハイスクールＤ×Ｄ HERO',
        abbr: 'DDH',
        enName: 'High School DxD Hero',
        releaseDate: 'Dec 12, 2018',
      },
      {
        jpName: '電波女と青春男',
        abbr: 'DNP',
        enName: 'Denpa Onna',
        releaseDate: 'Dec 16, 2011',
      },
      {
        jpName: '劇場版 ダンジョンに出会いを求めるのは間違っているだろうか ―オリオンの矢―',
        abbr: 'DNMC',
        enName: 'Is It Wrong to Try to Pick Up Girls in a Dungeon?: Arrow of the Orion',
        releaseDate: 'Sep 27, 2019',
      },
      {
        jpName: 'ダンジョンに出会いを求めるのは間違っているだろうかⅡ',
        abbr: 'DNMC2',
        enName: 'Is It Wrong to Try to Pick Up Girls in a Dungeon? II',
        releaseDate: 'Dec 18 2020',
      },
      {
        jpName: '私、能力は平均値でって言ったよね！',
        abbr: 'NUKN',
        enName: "Didn't I Say to Make My Abilities Average in the Next Life?!",
        releaseDate: 'Jul 24, 2020',
      },
      {
        jpName: 'エロマンガ先生',
        abbr: 'ERMG',
        enName: 'Eromanga Sensei',
        releaseDate: 'Mar 30, 2018',
      },
      {
        jpName: 'フレームアームズ・ガール',
        abbr: 'FA',
        enName: 'Frame Arms Girl',
        releaseDate: 'Aug 24, 2018',
      },
      {
        jpName: 'がっこうぐらし！',
        abbr: 'GG',
        enName: 'Gakkougurashi! (School-Live!)',
        releaseDate: 'Feb 12, 2016',
      },
      {
        jpName: '五等分の花嫁',
        abbr: 'GOTO',
        enName: 'The Quintessential Quintuplets',
        releaseDate: 'Feb 28, 2020',
      },
      {
        jpName: 'ガールズ＆パンツァー',
        abbr: 'GP',
        enName: 'Girls & Panzer',
        releaseDate: 'Nov 8, 2013',
      },
      {
        jpName: 'ガールズ＆パンツァー　劇場版',
        abbr: 'GPF',
        enName: 'Girls & Panzer Movie',
        releaseDate: 'Aug 26, 2016',
      },
      {
        jpName: 'ガールズ＆パンツァー 最終章',
        abbr: 'GPFN',
        enName: 'Girls & Panzer Final Chapter',
        releaseDate: 'Sep 13, 2019',
      },
      {
        jpName: 'グランベルム',
        abbr: 'GRAN',
        enName: 'Granbelm',
        releaseDate: 'Jan 24, 2020',
      },
      {
        jpName: '八月のシンデレラナイン',
        abbr: 'HCNI',
        enName: 'Hachigatsu no Cinderella Nine',
        releaseDate: 'Oct 25, 2019',
      },
      {
        jpName: 'ハロー！！きんいろモザイク',
        abbr: 'HKM',
        enName: 'Hello!! Kiniro Mosaic',
        releaseDate: 'Oct 9, 2015',
      },
      {
        jpName: '初音ミク',
        abbr: 'HMK',
        enName: 'Hatsune Miku',
        releaseDate: 'Mar 9, 2013',
      },
      {
        jpName: '初音ミクPart.2',
        abbr: 'HMK',
        enName: 'Hatsune Miku Part.2',
        releaseDate: 'Aug 31, 2013',
      },
      {
        jpName: '初音ミクPart.3',
        abbr: 'HMK',
        enName: 'Hatsune Miku Part.3',
        releaseDate: 'Mar 9, 2015',
      },
      {
        jpName: 'ハンドシェイカー',
        abbr: 'HND',
        enName: 'Handshakers',
        releaseDate: 'Apr 27, 2017',
      },
      {
        jpName: 'ハナヤマタ',
        abbr: 'HNYM',
        enName: 'Hanayamata',
        releaseDate: 'Feb 20, 2015',
      },
      {
        jpName: 'ひだまりスケッチ',
        abbr: 'HS',
        enName: 'Hidamari Sketch',
        releaseDate: '??? ??, 2012',
      },
      {
        jpName: 'ひだまりスケッチ×ハニカム',
        abbr: 'HS4',
        enName: 'Hidamari Sketch X Honeycomb',
        releaseDate: 'Dec 6, 2013',
      },
      {
        jpName: '百花繚乱 サムライブライド',
        abbr: 'HSB',
        enName: 'Hyakka Ryouran: Samurai Bride',
        releaseDate: 'Jun 15, 2014',
      },
      {
        jpName: 'ハイスクール・フリート',
        abbr: 'HSF',
        enName: 'Highschool Fleet',
        releaseDate: 'Jun 23, 2017',
      },
      {
        jpName: '劇場版 ハイスクール・フリート',
        abbr: 'HSFM',
        enName: 'High School Fleet Movie',
        releaseDate: 'Feb 21, 2020',
      },
      {
        jpName: 'はたらく細胞',
        abbr: 'HTRK',
        enName: 'Cells at Work',
        releaseDate: 'Mar 22, 2019',
      },
      {
        jpName: '百花繚乱 サムライガールズ',
        abbr: 'hyakka',
        enName: 'Hyakka Ryouran: Samurai Girls',
        releaseDate: '??? ??, 2011',
      },
      {
        jpName: '侵略！イカ娘',
        abbr: 'IKA',
        enName: 'The Squid Girl',
        releaseDate: '??? ??, 2012',
      },
      {
        jpName: '侵略!?イカ娘',
        abbr: 'IKA2',
        enName: 'The Squid Girl 2',
        releaseDate: 'Sep 28, 2012',
      },
      {
        jpName: 'ココロコネクト',
        abbr: 'KC',
        enName: 'Kokoro Connect',
        releaseDate: 'Mar 29, 2013',
      },
      {
        jpName: '刀語',
        abbr: 'KG',
        enName: 'Katanagatari',
        releaseDate: '??? ??, 2011',
      },
      {
        jpName: '怪獣娘（黒）',
        abbr: 'KGB',
        enName: 'Kaijuu Girls Black',
        releaseDate: '??? ??, 2020',
      },
      {
        jpName: 'かぐや様は告らせたい～天才たちの恋愛頭脳戦～',
        abbr: 'KGY',
        enName: 'Kaguya-sama: Love is War Season 2',
        releaseDate: 'Nov 29, 2019',
      },
      {
        jpName: 'きんいろモザイク',
        abbr: 'KMK',
        enName: 'Kiniro Mosaic (KINMOZA!)',
        releaseDate: 'Feb 21, 2014',
      },
      {
        jpName: '神様のメモ帳',
        abbr: 'KM',
        enName: "Heaven's Memo Pad",
        releaseDate: 'May 25, 2012',
      },
      {
        jpName: '傷物語',
        abbr: 'KMG',
        enName: 'Kizumonogatari',
        releaseDate: 'Oct 23, 2020',
      },
      {
        jpName: 'きんいろモザイク Pretty Days',
        abbr: 'KMPD',
        enName: 'Hello!! Kiniro Mosaic Special',
        releaseDate: '??? ??, 2017',
      },
      {
        jpName: 'ケムリクサ',
        abbr: 'KMR',
        enName: 'Kemurikusa',
        releaseDate: 'Jun 26, 2019',
      },
      {
        jpName: 'けいおん！',
        abbr: 'KON',
        enName: 'K-ON!',
        releaseDate: '??? ??, 2011',
      },
      {
        jpName: 'けいおん！Part2',
        abbr: 'K-ON_Part2',
        enName: 'K-ON! Part.2',
        releaseDate: 'May 28, 2012',
      },
      {
        jpName: 'けいおん！！',
        abbr: 'KON3',
        enName: 'K-ON!!',
        releaseDate: 'May 28, 2012',
      },
      {
        jpName: 'けいおん！！Part.2',
        abbr: 'KON4',
        enName: 'K-ON!! Part.2',
        releaseDate: 'May 28, 2012',
      },
      {
        jpName: '映画「けいおん！」',
        abbr: 'KONM',
        enName: 'K-ON! Movie',
        releaseDate: 'Aug 1, 2016',
      },
      {
        jpName: '恋と選挙とチョコレート',
        abbr: 'KSC',
        enName: 'Love, Election and Chocolate',
        releaseDate: 'May 31, 2013',
      },
      {
        jpName: '恋愛ラボ',
        abbr: 'LL',
        enName: 'Love Lab',
        releaseDate: 'Apr 4, 2014',
      },
      {
        jpName: 'まよチキ！',
        abbr: 'MC',
        enName: 'Mayo Chiki!',
        releaseDate: 'Feb 29, 2012',
      },
      {
        jpName: '魔法少女まどか☆マギカ',
        abbr: 'MDK',
        enName: 'Mahou Shoujo Madoka★Magica',
        releaseDate: 'Aug 26, 2011',
      },
      {
        jpName: '劇場版 魔法少女まどか☆マギカ',
        abbr: 'MMDK',
        enName: 'Puella Magi Madoka Magica the Movie',
        releaseDate: 'Jun 28, 2013',
      },
      {
        jpName: '劇場版 魔法少女まどか☆マギカ[新編]叛逆の物語',
        abbr: 'MMH',
        enName: 'Puella Magi Madoka Magica the Movie: Rebellion',
        releaseDate: 'Oct 17, 2014',
      },
      {
        jpName: 'ましろ色シンフォニー',
        abbr: 'MS',
        enName: 'Mashiro-iro Symphony',
        releaseDate: 'Feb 29, 2011',
      },
      {
        jpName: '<物語>シリーズ セカンドシーズン',
        abbr: 'MG2',
        enName: 'Monogatari Series: Second Season',
        releaseDate: 'Sep 19, 2014',
      },
      {
        jpName: '<物語>シリーズ',
        abbr: 'MGS',
        enName: 'Monogatari Series',
        releaseDate: 'Jul 31, 2015',
      },
      {
        jpName: '<物語>シリーズ セカンドシーズン',
        abbr: 'MGS2',
        enName: 'Monogatari Series Second Season',
        releaseDate: 'Sep 19, 2014',
      },
      {
        jpName: '劇場版 魔法科高校の劣等生 星を呼ぶ少女',
        abbr: 'MHK',
        enName: 'The Irregular at Magic High School',
        releaseDate: 'Nov 17, 2017',
      },
      {
        jpName: '魔法科高校の劣等生 来訪者編',
        abbr: 'MHK2',
        enName: 'The Irregular at Magic High School: Visitor Arc',
        releaseDate: 'Apr 30, 2021',
      },
      {
        jpName: 'みなみけ',
        abbr: 'MMK',
        enName: 'Minami-ke',
        releaseDate: 'Nov 29, 2013',
      },
      {
        jpName: 'まちカドまぞく',
        abbr: 'MZK',
        enName: 'The Demon Girl Next Door',
        releaseDate: 'Mar 27, 2020',
      },
      {
        jpName: 'ネコぱら',
        abbr: 'NEKO',
        enName: 'Neko Para',
        releaseDate: 'Aug 28, 2020',
      },
      {
        jpName: 'NEW GAME!',
        abbr: 'NG',
        enName: 'New Game!',
        releaseDate: '??? ??, 2017',
      },
      {
        jpName: 'NEW GAME!!',
        abbr: 'NG2',
        enName: 'New Game!!',
        releaseDate: 'Jul 27, 2018',
      },
      {
        jpName: 'ノーゲーム・ノーライフ ゼロ',
        abbr: 'NGNL',
        enName: 'No Game No Life: Zero',
        releaseDate: 'Feb 23, 2018',
      },
      {
        jpName: '夏色キセキ',
        abbr: 'NK',
        enName: 'Natsu-iro Kiseki',
        releaseDate: 'Oct 26, 2012',
      },
      {
        jpName: '偽物語',
        abbr: 'NMG',
        enName: 'Nisemonogatari',
        releaseDate: 'Nov 23, 2013',
      },
      {
        jpName: 'おちこぼれフルーツタルト',
        abbr: 'OCFR',
        enName: 'Idol Dropout Fruit Tart',
        releaseDate: 'Aug 27, 2021',
      },
      {
        jpName: 'やはり俺の青春ラブコメはまちがっている。',
        abbr: 'OGR',
        enName: 'My Teen Romantic Comedy SNAFU',
        releaseDate: 'Dec 4, 2015',
      },
      {
        jpName: 'オオカミさんと七人の仲間たち',
        abbr: 'ookami',
        enName: 'Okami-San and Her Seven Companions',
        releaseDate: '??? ??, 2011',
      },
      {
        jpName: '俺の彼女と幼なじみが修羅場すぎる',
        abbr: 'OOS',
        enName: 'Oreshura',
        releaseDate: 'Oct 25, 2013',
      },
      {
        jpName: '俺を好きなのはお前だけかよ',
        abbr: 'ORSK',
        enName: 'ORESUKI Are you the only one who loves me?',
        releaseDate: 'Jun 26, 2020',
      },
      {
        jpName: '俺の妹がこんなに可愛いわけがない',
        abbr: 'oreimo',
        enName: 'My Little Sister Can’t Be This Cute',
        releaseDate: 'Aug 22, 2011',
      },
      {
        jpName: '俺の妹がこんなに可愛いわけがない。',
        abbr: 'ORE2',
        enName: 'My Little Sister Can’t Be This Cute 2',
        releaseDate: 'Dec 7, 2012',
      },
      {
        jpName: 'やはり俺の青春ラブコメはまちがっている。完',
        abbr: 'OREG3',
        enName: 'My Teen Romantic Comedy SNAFU Climax! ',
        releaseDate: 'Mar 26, 2021',
      },
      {
        jpName: 'やはり俺の青春ラブコメはまちがっている。続',
        abbr: 'ORG2',
        enName: 'My Teen Romantic Comedy SNAFU TOO!',
        releaseDate: 'Dec 4, 2015',
      },
      {
        jpName: 'ポプテピピック',
        abbr: 'PPTP',
        enName: 'POP TEAM EPIC',
        releaseDate: 'Feb 22, 2019',
      },
      {
        jpName: 'STEINS;GATE',
        abbr: 'SG',
        enName: 'STEINS;GATE',
        releaseDate: 'Jan 25, 2019',
      },
      {
        jpName: 'さくら荘のペットな彼女',
        abbr: 'SPK',
        enName: 'The Pet Girl of Sakurasou',
        releaseDate: 'Sep 29, 2013',
      },
      {
        jpName: 'RELEASE THE SPYCE',
        abbr: 'SPY',
        enName: 'RELEASE THE SPYCE',
        releaseDate: 'May 24, 2019',
      },
      {
        jpName: 'SHIROBAKO',
        abbr: 'SRBK',
        enName: 'Shirobako',
        releaseDate: '??? ??, 2015',
      },
      {
        jpName: '劇場版「SHIROBAKO」',
        abbr: 'SRBKM',
        enName: 'Shirobako Movie',
        releaseDate: 'Apr 24, 2020',
      },
      {
        jpName: 'SSSS.GRIDMAN',
        abbr: 'SSSS',
        enName: 'SSSS.GRIDMAN',
        releaseDate: 'Apr 26, 2019',
      },
      {
        jpName: '生徒会の一存 Lv.2',
        abbr: 'SZ2',
        enName: "Student Council's Discretion Level 2",
        releaseDate: 'Feb 22, 2013',
      },
      {
        jpName: 'ささみさん＠がんばらない',
        abbr: 'SAG',
        enName: 'Sasami-san@Ganbarai',
        releaseDate: 'Dec 27, 2013',
      },
      {
        jpName: 'ゾンビランドサガ',
        abbr: 'SAGA',
        enName: 'Zombieland Saga',
        releaseDate: 'Jun 28, 2019',
      },
      {
        jpName: '咲-Saki- 全国編',
        abbr: 'SAK',
        enName: 'Saki: The Nationals',
        releaseDate: 'Dec 05, 2014',
      },
      {
        jpName: '冴えない彼女の育てかた',
        abbr: 'SEKN',
        enName: 'How to Raise a Boring Girlfriend',
        releaseDate: '??? ??, 2015',
      },
      {
        jpName: 'とある科学の超電磁砲＆とある科学の超電磁砲Ｓ',
        abbr: 'TKR',
        enName: 'A Certain Scientific Railgun & A Certain Scientific Railgun S',
        releaseDate: 'Nov 11, 2016',
      },
      {
        jpName: 'とある科学の超電磁砲T',
        abbr: 'TKRT',
        enName: 'A Certain Scientific Railgun T',
        releaseDate: 'Sep 25, 2020',
      },
      {
        jpName: 'とらドラ！',
        abbr: 'TRDR',
        enName: 'Toradora!',
        releaseDate: 'Jul 27, 2012',
      },
      {
        jpName: '魔法使いの夜',
        abbr: 'WHN',
        enName: 'Witch of the Holy Night',
        releaseDate: 'Sep 9, 2013',
      },
      {
        jpName: 'WORKING！！',
        abbr: 'WKG',
        enName: 'WORKING!!',
        releaseDate: 'May 29, 2012',
      },
      {
        jpName: 'WORKING´!!',
        abbr: 'WKG2',
        enName: 'WORKING´!!',
        releaseDate: 'Jun 29, 2012',
      },
      {
        jpName: 'WORKING!!!',
        abbr: 'WKG3',
        enName: 'WORKING!!!',
        releaseDate: 'Apr 15, 2016',
      },
      {
        jpName: 'ゆるキャン△',
        abbr: 'YRC',
        enName: 'Yuru Camp△',
        releaseDate: 'Sep 28, 2018',
      },
      {
        jpName: 'ゆるゆり、',
        abbr: 'YRYR10',
        enName: 'Yuru Yuri,',
        releaseDate: 'Jun 12, 2020',
      },
      {
        jpName: 'ゆるゆり　なちゅやちゅみ！',
        abbr: 'YRYRN',
        enName: 'Yuru Yuri Nachuyachumi!',
        releaseDate: 'May 5, 2015',
      },
      {
        jpName: 'ゆるゆり♪♪',
        abbr: 'YRYR2',
        enName: 'YuruYuri: Happy Go Lily ♪♪',
        releaseDate: 'Sep 13, 2013',
      },
      {
        jpName: 'ゆるゆり',
        abbr: 'YRYR',
        enName: 'YuruYuri: Happy Go Lily',
        releaseDate: 'Mar 30, 2012',
      },
      {
        jpName: '結城友奈は勇者である',
        abbr: 'YYY',
        enName: 'Yuki Yuna is a Hero',
        releaseDate: '??? ?? 2018',
      },
      {
        jpName: '結城友奈は勇者である -鷲尾須美の章-/-勇者の章-',
        abbr: 'YYY2',
        enName: 'Yuki Yuna is a Hero: The Washio Sumi Chapter',
        releaseDate: 'Jun 29, 2018',
      }
    ]
  }
}